export const copy = {
  wordmark: "MD to PDF",
  download: "Download PDF",
  rendering: "Rendering…",
  themeToDark: "Switch to dark theme",
  themeToLight: "Switch to light theme",
  editorLabel: "Markdown",
  open: "Open",
  editorPlaceholder: "Write markdown here. It saves as you type.",
  editorTabHint: "Press Escape, then Tab, to leave the editor.",
  tabs: { write: "Write", preview: "Preview", html: "HTML", pdf: "PDF" },
  previewEmpty: "Nothing to preview yet.",
  htmlEmpty: "No HTML yet.",
  copy: "Copy",
  copied: "Copied",
  copyFailed: "Couldn't copy. Select the text and copy it instead.",
  update: "Update",
  tryAgain: "Try again",
  pageSizes: { A4: "A4", Letter: "Letter" },
  pageSize: "Page size",
  pdfError: "Couldn't render the PDF.",
  pdfRateLimited: "Too many requests. Wait a moment and try again.",
  pdfTooLarge: "The document is too large to render. Trim it to under 2 MB of HTML.",
  pdfNotConfigured: "PDF rendering isn't set up yet. Add the Cloudflare credentials to the Worker and restart.",
  pdfEngineError: "Couldn't load the PDF viewer.",
  pdfDocumentError: "Couldn't open the PDF.",
  openWrongType: "Open a .md, .markdown or .txt file.",
  replacedWith: (name: string) => `Replaced with ${name}.`,
  undo: "Undo",
  pdfFrameTitle: "PDF preview",
  words: (n: number) => `${n.toLocaleString("en-US")} ${n === 1 ? "word" : "words"}`,
  title: (doc: string) => (doc ? `${doc} · MD to PDF` : "MD to PDF"),
} as const;
